theme: minima
title: My jekyll style blog
author: Filifili User 
email: filifiliproject@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I want to use this style for a development diary of Filifili. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
